# Generated by Django 4.2.2 on 2023-06-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationattribute',
            old_name='attribute_name',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='specificationattribute',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='specificationattribute',
            name='product',
        ),
        migrations.CreateModel(
            name='SpecificationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_name', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='specificationattribute',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.specificationname'),
            preserve_default=False,
        ),
    ]
