# Generated by Django 4.2.2 on 2023-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
