# Generated by Django 4.2.2 on 2023-06-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_rating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationname',
            name='product',
        ),
        migrations.AddField(
            model_name='specificationattribute',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specification_name', to='product.product'),
            preserve_default=False,
        ),
    ]
