# Generated by Django 4.2.2 on 2023-06-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_specificationname_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_attributes', to='product.product'),
        ),
    ]
