# Generated by Django 4.2.1 on 2023-06-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_specification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
    ]
