# Generated by Django 4.2.2 on 2023-06-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_price_cart_total_price_cart_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_quantity',
        ),
    ]
