# Generated by Django 4.2.2 on 2023-06-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_name_alter_order_phone'),
        ('cart', '0003_remove_cart_total_price_remove_cart_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders_cart', to='orders.order'),
            preserve_default=False,
        ),
    ]
